on: 
  pull_request:

jobs:
  lint-commits:
    name: Commitlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          # we actually need "github.event.pull_request.commits + 1" commit
          fetch-depth: 0
      - uses: actions/setup-node@v2.2.0
      # or just "yarn" if you depend on "@commitlint/cli" already
      - run: yarn add @commitlint/cli
      - run: yarn run commitlint --from HEAD~${{ github.event.pull_request.commits }} --to HEAD