on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  jest:
    name: Jest
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4

    - name: install node v14
      uses: actions/setup-node@v2.1.5
      with:
        node-version: 14

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - uses: actions/cache@v2.1.5
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: yarn install
      run: yarn install

    - name: Jest
      run: yarn coverage
      env:
        TOKEN: ${{ secrets.KOREANBOTS_TOKEN }}
        CLIENT_ID: ${{ secrets.CLIENT_ID }}

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1.5.0
      with: 
          token: ${{ secrets.CODECOV_TOKEN }}
